import {
  product1,
  product2,
  product3,
  product4,
  product5,
  product6,
  product7,
  product8,
  product9,
  product10,
  product11,
  product12,
  product13,
  product14,
  product15,
  product16,
  product17,
  product18,
  product19,
  product20,
  product21,
  product22,
  product23,
  product24,
  product25,
  product26,
  product27,
  product28,
  product29,
  product30,
  product31,
  product32,
  product33,
  product34,
  product35,
  product36,
  product37,
  product38,
  product39,
  product40,
  product41,
  product42,
  product43,
  product44,
  product45,
  product46,
  product47,
  product48,
  product49,
  product50,
  product51,
  product52,
  product53,
  product54,
  product60,
  product61,
  product62,
  product63,
  product64,
  product65,
  product66,
  product67,
  product68,
  product69,
  product70,
  product71,
  product72,
  product73,
  product74,
  product75,
  product76,
  product77,
  employee1,
  employee2,
  employee3,
  employee4,
  employee5,
  employee6,
  employee7,
  employee8,
  employee9,
} from "../assets/images";

import {
  service1,
  service2,
  service3,
  service4,
  service5,
  service6,
  phone,
  mail,
  mastercard,
  visa,
  paypal,
} from "../assets/icons";

export const languages = [
  { id: "english", label: "English" },
  { id: "francaise", label: "Francaise" },
  { id: "spanish", label: "Spanish" },
  { id: "arabic", label: "العربية" },
];

export const navLinks = [
  { href: "", label: "Home" },
  { href: "about", label: "About" },
  { href: "contact", label: "Contact" },
  { href: "signup", label: "Sign Up" },
];

export const mobileLinks = [
  { href: "", label: "Home" },
  { href: "about", label: "About" },
  { href: "contact", label: "Contact" },
  { href: "signup", label: "Sign Up" },
  { href: "wishlist", label: "Wishlist" },
  { href: "cart", label: "Cart" },
];

export const homeLinks = [
  { icon: true, value: "Women's Fashion" },
  { icon: true, value: "Men's Fashion" },
  { icon: false, value: "Electronics" },
  { icon: false, value: "Home & Lifestyle" },
  { icon: false, value: "Medicine" },
  { icon: false, value: "Sports & Outdoor" },
  { icon: false, value: "Baby's & Toys" },
  { icon: false, value: "Groceries & Pets" },
  { icon: false, value: "Health & Beauty" },
];

export const time = [
  { id: 1, time: "Days", value: "03" },
  { id: 2, time: "Hours", value: "23" },
  { id: 3, time: "Minutes", value: "19" },
  { id: 4, time: "Seconds", value: "56" },
];

export const sales = [
  {
    img: product1,
    label: "iPhone 8",
    price: "214",
    oldPrice: "250",
    rate: "88",
    full: 4,
    empty: 1,
    half: 0,
    percent: "25",
  },
  {
    img: product5,
    label: "iPad Mini 3 - 16GB",
    price: "299",
    oldPrice: "320",
    rate: "129",
    full: 4,
    empty: 1,
    half: 0,
    percent: "20",
  },
  {
    img: product9,
    label: "Glaxy Book 3",
    price: "370",
    oldPrice: "440",
    rate: "99",
    full: 4,
    empty: 0,
    half: 1,
    percent: "30",
  },
  {
    img: product14,
    label: "Logitech C505",
    price: "35",
    oldPrice: "64",
    rate: "168",
    full: 4,
    empty: 0,
    half: 1,
    percent: "50",
  },
  {
    img: product43,
    label: "Razer Huntsman Mini",
    price: "25",
    oldPrice: "79",
    rate: "129",
    full: 4,
    empty: 1,
    half: 0,
    percent: "60",
  },
  {
    img: product49,
    label: "Razer Pro",
    price: "68",
    oldPrice: "99",
    rate: "129",
    full: 4,
    empty: 0,
    half: 1,
    percent: "30",
  },
];

export const categories = [
  {
    icon: "fa-solid fa-mobile-screen-button",
    label: "Phones",
    category: "phone",
  },
  { icon: "fa-solid fa-laptop", label: "Laptops", category: "laptop" },
  { icon: "fa-solid fa-camera", label: "Camera", category: "camera" },
  {
    icon: "fa-solid fa-headphones-simple",
    label: "Head Phones",
    category: "headPhones",
  },
  { icon: "fa-solid fa-gamepad", label: "Consoles", category: "console" },
  { icon: "fa-solid fa-display", label: "Monitors", category: "monitor" },
  { icon: "fa-regular fa-keyboard", label: "Keyboard", category: "keyboard" },
  { icon: "fa-solid fa-computer-mouse", label: "Mouses", category: "mouse" },
  { icon: "fa-solid fa-computer", label: "PC Gamer", category: "pc" },
];

export const bestSelling = [
  {
    img: product54,
    label: "Razer Basilisk V3",
    price: "189",
    oldPrice: "",
    rate: "45",
    full: 4,
    empty: 1,
    half: 0,
    percent: null,
  },
  {
    img: product10,
    label: "Razer Blade 15",
    price: "1650",
    oldPrice: "",
    rate: "142",
    full: 4,
    empty: 1,
    half: 0,
    percent: null,
  },
  {
    img: product23,
    label: "PlayStation 5 Pulse",
    price: "93",
    oldPrice: "",
    rate: "240",
    full: 4,
    empty: 0,
    half: 1,
    percent: null,
  },
  {
    img: product35,
    label: "Nvidia RTX 3060, Core i9, 16GB RAM",
    price: "8410",
    oldPrice: "",
    rate: "41",
    full: 5,
    empty: 0,
    half: 0,
    percent: null,
  },
];

export const services = [
  {
    icon: service1,
    title: "FREE AND FAST DELIVERY",
    value: "Free delivery for all orders over $1000",
  },
  {
    icon: service2,
    title: "Order Tracking",
    value:
      "Enable easy track orders from the moment they are shipped until they are delivered.",
  },
  {
    icon: service3,
    title: "International Shipping",
    value: "We offer international shipping",
  },
  {
    icon: service4,
    title: "Product Demos",
    value: "Create video demos to showcase your products in action",
  },
  {
    icon: service5,
    title: "MONEY BACK GUARANTEE",
    value: "We reurn money within 30 days",
  },
  {
    icon: service6,
    title: "24/7 CUSTOMER SERVICE",
    value: "Friendly 24/7 customer support",
  },
];

export const products = [
  {
    img: product1,
    name: "iPhone 8 Plus 258GB",
    price: "250",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "1",
    rate: "128",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product2,
    name: "iPhone 8 126GB",
    price: "200",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "180",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product62,
    name: "iPhone 14 plus",
    price: "380",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "298",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product63,
    name: "iPhone 14 ",
    price: "420",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "311",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product3,
    name: "Galaxy S10+",
    price: "420",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "86",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product4,
    name: "Galaxy A20 Black 32GB",
    price: "340",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "122",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product5,
    name: "iPad Mini 3 - 16GB",
    price: "320",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "125",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product6,
    name: "Galaxy Tab A9 LTE",
    price: "295",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "310",
    category: "phone",
    oldPrice: "",
    percent: null,
  },
  {
    img: product7,
    name: "MacBook Pro",
    price: "590",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "329",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product8,
    name: "HP Laptop 15-dw",
    price: "316",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "178",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product9,
    name: "Galaxy Book 3",
    price: "440",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "89",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product10,
    name: "Razer Blade 15",
    price: "1650",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "142",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product11,
    name: "Razer Blade17",
    price: "1999",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "215",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product12,
    name: "ASUS X415",
    price: "490",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "102",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product60,
    name: " ROG Global",
    price: "2100",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "185",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product61,
    name: "MSI GF Thin 10SER",
    price: "1880",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "316",
    category: "laptop",
    oldPrice: "",
    percent: null,
  },
  {
    img: product13,
    name: "Logitech StreamCam",
    price: "2709",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "58",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product14,
    name: "Logitech C505",
    price: "64",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "168",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product15,
    name: "Razer Kiyo",
    price: "81",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "325",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product16,
    name: "Logitech C920e",
    price: "359",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "214",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product17,
    name: "GoPro Hero 9",
    price: "197",
    startsFull: "3",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "82",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product18,
    name: "GoPro Hero 10",
    price: "215",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "115",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product76,
    name: "GoPro Hero 11",
    price: "314",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "187",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product77,
    name: "GoPro Hero 12",
    price: "410",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "78",
    category: "camera",
    oldPrice: "",
    percent: null,
  },
  {
    img: product19,
    name: "HyperX Cloud || ",
    price: "80",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "340",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product20,
    name: "Cloud Flight ",
    price: "159",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "128",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product21,
    name: "Razer Kraken V3 Pro",
    price: "194",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "98",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product22,
    name: "Razer Kraken Ultimate",
    price: "135",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "198",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product23,
    name: "PlayStation 5 Pulse",
    price: "93",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "240",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product66,
    name: "ROG Delta",
    price: "87",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "12",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product67,
    name: "Logitech G233",
    price: "130",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "278",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product24,
    name: "AirPods Max",
    price: "130",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "320",
    category: "headPhones",
    oldPrice: "",
    percent: null,
  },
  {
    img: product25,
    name: "PlayStation 5",
    price: "399",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "329",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product26,
    name: "Xbox series x",
    price: "459",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "186",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product27,
    name: "Wii",
    price: "149",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "87",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product28,
    name: "Apple Vision Pro VR",
    price: "3804",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "76",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product29,
    name: "Nintendo Switch",
    price: "259",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "178",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product30,
    name: "Meta VR",
    price: "189",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "92",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product70,
    name: "Playstation 4",
    price: "165",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "325",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product71,
    name: "Xbox One",
    price: "314",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "182",
    category: "console",
    oldPrice: "",
    percent: null,
  },
  {
    img: product31,
    name: "Nvidia 1050 TI 2GB, Core i7, 16GB RAM",
    price: "3800",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "412",
    category: "pc",
    oldPrice: "",
    percent: null,
  },
  {
    img: product32,
    name: "Nvidia 1060 TI 4GB, Core i7, 16GB RAM",
    price: "3999",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "358",
    category: "pc",
    oldPrice: "",
    percent: null,
  },
  {
    img: product33,
    name: "Nvidia 1050 TI 4GB, Core i9, 16GB RAM",
    price: "4400",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "169",
    category: "pc",
    oldPrice: "",
    percent: null,
  },
  {
    img: product34,
    name: "Nvidia 1080 4GB, Core i9, 16GB RAM",
    price: "4950",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "139",
    category: "pc",
    oldPrice: "",
    percent: null,
  },
  {
    img: product35,
    name: "Nvidia RTX 3060, Core i9, 16GB RAM",
    price: "8410",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "41",
    category: "pc",
    oldPrice: "",
    percent: null,
  },
  {
    img: product36,
    name: "Nvidia RTX 3080, Core i9, 32GB RAM",
    price: "9100",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "67",
    category: "pc",
    oldPrice: "",
    percent: null,
  },

  {
    img: product69,
    name: "Nvidia RTX 4060 Ti, Core i9, 32GB RAM",
    price: "9999",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "57",
    category: "pc",
    oldPrice: "",
    percent: null,
  },
  {
    img: product68,
    name: "Nvidia  4080 SUPER, Core i9, 32GB RAM",
    price: "11000",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "23",
    category: "pc",
    oldPrice: "",
    percent: null,
  },
  {
    img: product37,
    name: "ASUS 144HZ Monitor",
    price: "180",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "124",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product38,
    name: "IPS LCD Gaming Monitor",
    price: "110",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "88",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product39,
    name: "J6300 6Series Curved",
    price: "130",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "241",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product40,
    name: "ASUS monitor",
    price: "210",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "123",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product41,
    name: "KOORIU 26E3A",
    price: "60",
    startsFull: "3",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "41",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product42,
    name: "MSI Monitor 144HZ",
    price: "199",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "514",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product64,
    name: "MSI 27 Curved Gaming",
    price: "210",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "258",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product65,
    name: "Razer Raptor 27 165Hz",
    price: "235",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "89",
    category: "monitor",
    oldPrice: "",
    percent: null,
  },
  {
    img: product43,
    name: "Razer Huntsman Mini",
    price: "79",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "1",
    rate: "89",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product44,
    name: "Razer BlackWidow V4 ||",
    price: "289",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "112",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product45,
    name: "ASUS BlackWidow",
    price: "129",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "259",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product46,
    name: "Razer BlackWidow V4",
    price: "299",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "354",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product47,
    name: "Razer BlackWidow mini",
    price: "139",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "74",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product48,
    name: "Logitech G Pro X",
    price: "249",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "236",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product72,
    name: "AK-900 Wired Keyboard",
    price: "249",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "236",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product73,
    name: "Razer Huntsman Mini ||",
    price: "249",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "236",
    category: "keyboard",
    oldPrice: "",
    percent: null,
  },
  {
    img: product74,
    name: "Entwino Ranger",
    price: "56",
    startsFull: "3",
    starsHalf: "0",
    starsEmpty: "2",
    rate: "192",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },

  {
    img: product49,
    name: "Razer Pro",
    price: "99",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "129",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },
  {
    img: product50,
    name: "G502 Lightspeed ",
    price: "87",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "219",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },
  {
    img: product51,
    name: "Wireless Gaming Mouse",
    price: "69",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "87",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },
  {
    img: product52,
    name: "Razer Firely V2",
    price: "86",
    startsFull: "4",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "149",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },
  {
    img: product53,
    name: "Logitech Pro",
    price: "130",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "158",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },
  {
    img: product54,
    name: "Razer Basilisk V3",
    price: "189",
    startsFull: "4",
    starsHalf: "1",
    starsEmpty: "0",
    rate: "45",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },
  {
    img: product75,
    name: "Razer DEATHADDER",
    price: "249",
    startsFull: "5",
    starsHalf: "0",
    starsEmpty: "0",
    rate: "236",
    category: "mouse",
    oldPrice: "",
    percent: null,
  },
];
export const stats = [
  {
    icon: "fa-solid fa-store",
    label: "Sallers active our site",
    value: "10.5 K",
  },
  {
    icon: "fa-solid fa-dollar-sign",
    label: "Monthly Produduct Sale",
    value: "30 K",
  },
  {
    icon: "fa-solid fa-bag-shopping",
    label: "Customer active in our site",
    value: "45.7 K",
  },
  {
    icon: "fa-solid fa-sack-dollar",
    label: "Anual gross sale in our site",
    value: "25 K",
  },
];

export const employees = [
  {
    id: 1,
    phase: 0,
    name: "Mark Johnson",
    img: employee1,
    job: "CEO",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 2,
    phase: 0,
    name: "Andrew Johnson",
    img: employee2,
    job: "Co-Founder",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 3,
    phase: 0,
    name: "Matthew Davis",
    img: employee3,
    job: "Chief Technology Officer",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 4,
    phase: 1,
    name: "Ryan Martinez",
    img: employee4,
    job: "Chief Operating Officer",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 5,
    phase: 1,
    name: "Christopher Lee",
    img: employee5,
    job: "Chief Financial Officer",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 6,
    phase: 1,
    name: "Jason Miller",
    img: employee6,
    job: "Head of Marketing",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 7,
    phase: 2,
    name: "Nicholas Taylor",
    img: employee7,
    job: "Head of Product Development",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 8,
    phase: 2,
    name: "Emma Watson",
    img: employee8,
    job: "Managing Director",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
  {
    id: 9,
    phase: 2,
    name: "Daniel Clark",
    img: employee9,
    job: "Chief Sales Officer",
    socials: [
      { icon: "fa-brands fa-x-twitter" },
      { icon: "fa-brands fa-instagram" },
      { icon: "fa-brands fa-linkedin-in" },
    ],
  },
];

export const signup = [
  { placeholder: "Name", type: "text" },
  { placeholder: "Email or Phone Number" },
  { placeholder: "Password", type: "password" },
];

export const login = [
  { placeholder: "Email or Phone Number", type: "email" },
  { placeholder: "Password", type: "password" },
];

export const footerLinks = [
  {
    label: "Support",
    links: [
      {
        href: "/",
        value: "93000 Tetouan,",
      },
      { href: "/", value: "Morocco" },
      { href: "/", value: "techshop@gmail.com" },
      { href: "/", value: "+212-666-8888" },
    ],
  },
  {
    label: "Account",
    links: [
      { href: "/", value: "My Account" },
      { href: "/", value: "Login / Register" },
      { href: "/", value: "Cart" },
      { href: "/", value: "Wishlist" },
      { href: "/", value: "Shop" },
    ],
  },
  {
    label: "Quick Link",
    links: [
      { href: "/", value: "Privacy Policy" },
      { href: "/", value: "Terms Of Use" },
      { href: "/", value: "FAQ" },
      { href: "/", value: "Contact" },
    ],
  },
];

export const socials = [
  { icon: "fa-brands fa-facebook-f", label: "facebook" },
  { icon: "fa-brands fa-x-twitter", label: "twitter" },
  { icon: "fa-brands fa-instagram", label: "instagram" },
  { icon: "fa-brands fa-whatsapp", label: "whatsapp" },
];

export const contact = [
  {
    img: phone,
    label: "Call To Us",
    informations: [
      { label: "We are available 24/7, 7 days a week." },
      { label: "Phone: +212-666-8888" },
    ],
    line: true,
  },
  {
    img: mail,
    label: "Write To US",
    informations: [
      { label: "Fill out our form and we will contact you within 24 hours." },
      { label: "Emails: customer@techshop.com" },
      { label: "Emails: support@techshop.com" },
    ],
    line: false,
  },
];

export const contactInputs = [
  { label: "Your Name", type: "text" },
  { label: "Your Email", type: "email" },
  { label: "Subject", type: "text" },
];

export const cartbar = [
  { name: "Product", positon: "" },
  { name: "Price", positon: "center" },
  { name: "Quantity", positon: "center" },
  { name: "Subtotal", positon: "end" },
];

export const billingInformations = [
  { label: "First Name", type: "text", optional: false },
  { label: "Street Address", type: "text", optional: false },
  { label: "Apartment,Floor,ect, (Optional)", type: "text", optional: true },
  { label: "Town / City", type: "text", optional: false },
  { label: "ZIP Code ", type: "text", optional: false },
  { label: "Phone Number", type: "text", optional: false },
  { label: "Email Address", type: "email", optional: false },
];

export const paymethods = [
  {
    name: "Bank",
    option: "option1",
    icon: true,
    icons: [{ icon: visa }, { icon: mastercard }, { icon: paypal }],
  },
  {
    name: "Cash on delivery",
    option: "option2",
    icon: false,
  },
];
